### ISSUE TITLE
Integrate Options into Default Addons UI

### ISSUE THREAD

**Issue by amiyuy** [TorelTwiddler/AntiDaze#4]
Switch from custom options menu to default UI Interface > Addons

**Comment by amiyuy** [comment]
- http://wow.gamepedia.com/Using_the_Interface_Options_Addons_panel
- https://us.battle.net/support/en/article/download-the-world-of-warcraft-interface-addon-kit

**Comment by TorelTwiddler** [comment]
Done, will be in release 6.1.0.1.
